### ISSUE TITLE
Unable to determine default CMAKE_INSTALL_LIBDIR

### ISSUE THREAD

**Issue by Germano0** [open-eid/firefox-pkcs11-loader#10]
I was building firefox-pkcs11-loader using the procedure in README file, when I got errors

```
$ cmake ..
CMake Warning (dev) at /usr/share/cmake/Modules/GNUInstallDirs.cmake:237 (message):
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
Call Stack (most recent call first):
  CMakeLists.txt:33 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/firefox-pkcs11-loader/build
```

OS: Fedora 27

**Comment by metsma** [comment]
I don't see any error, only warnings
"This warning is for project developers.  Use -Wno-dev to suppress it."

**Comment by Germano0** [comment]
The warnings probably lead to this problem I am experiencing in building RPMs
[%{_lib} leads to dir not found, whereas lib works fine (firefox-pkcs11-loader)](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/BLHQYSQOUTIRSJGVJBDBHGJO7WRRED3S/)

**Comment by metsma** [comment]
why not define then correct CMAKE_INSTALL_LIBDIR with cmake parameters?

**Comment by Germano0** [comment]
> The warnings probably lead to this problem I am experiencing in building RPMs
> %{_lib} leads to dir not found, whereas lib works fine (firefox-pkcs11-loader)

I was wrong

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/AHE3CKSZU2L4QZPJOAXZDUXJL2BZSKSQ/

> noarch only builds do not have %{_lib} or %{_libdir} defined 

Feel free to close the ticket :-)

Update: I am investigating about such RPM spec macros in noarch environment and I am currently reading https://pagure.io/packaging-committee/issue/203

**Comment by Germano0** [comment]
Concerning noarch: the noarch attribute has been removed after having read the suggestions of  Björn Persson
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/PSMY5RIDMSH33OKOXBN6MHP232MH7JKV/

**Comment by metsma** [comment]
You can use cmake parameter -DCMAKE_INSTALL_LIBDIR=/usr/... to fix location in spec file
