### ISSUE TITLE
Include firefox-pkcs11-loader in OpenSC

### ISSUE THREAD

**Issue by frankmorgner** [open-eid/firefox-pkcs11-loader#12]
I think it would be great for many users to have this in the default installer of OpenSC... What do you think?

**Comment by martinpaljak** [comment]
All extensions are best installed via the browser walled garden (read: app/extension store) so installation media might not matter that much

**Comment by metsma** [comment]
webextension needs additional registry keys and json files to have permission install module.
Similar to chrome native messaging
See: https://github.com/open-eid/firefox-pkcs11-loader/blob/master/onepinopenscpkcs11_Sys32.json

**Comment by kristelmerilain** [comment]
Feel free to use code.

**Comment by frankmorgner** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests for reference
