### ISSUE TITLE
Provide a cleanup method via extension preferences

### ISSUE THREAD

**Issue by martinpaljak** [open-eid/firefox-pkcs11-loader#15]
Loaded module causes issues with the system. I am able to track it down to the loaded PKCS#11 module. The extension can not be deleted, so the only action it provides via Firefox UI is "disable". It would be nice if the extension was either deletable, or would clean up (remove the PKCS#11 module) if it is deactivated or provide a preference pane that would allow to "logically disable" the extension (which would result in uninstalled PKCS#11 module).

Right now the only way to fix it is to 1) disable (or uninstall if possible) the extension 2) manually delete the module from security devices.

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the active development and management of the Firefox PKCS11 Loader component has ended due to the transition to the OpenSC pkcs11-register tool.
