### ISSUE TITLE
Link in the project description is broken

### ISSUE THREAD

**Issue by tari3x** [open-eid/firefox-pkcs11-loader#20]
This does not exist:
https://addons.mozilla.org/en-US/firefox/addon/est-pkcs11-load/

**Comment by metsma** [comment]
Thank you, removed.
We only distribute by package because the opensc-pkcs11 driver is also needed.
Signed extension is available here
https://github.com/open-eid/firefox-pkcs11-loader/blob/master/%7B02274e0c-d135-45f0-8a9c-32b35110e10d%7D.xpi
