### ISSUE TITLE
openSuSE support

### ISSUE THREAD

**Issue by tari3x** [open-eid/firefox-pkcs11-loader#21]
How do I make the ID card work for authentication (say, for entering eesti.ee) work on SuSE? 

I tried building this package, but I get:
```
> make installer 
Scanning dependencies of target installer
[100%] Creating installer
make[3]: dh_make: Command not found
make[3]: *** [CMakeFiles/installer.dir/build.make:58: CMakeFiles/installer] Error 127
make[2]: *** [CMakeFiles/Makefile2:68: CMakeFiles/installer.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/installer.dir/rule] Error 2
make: *** [Makefile:152: installer] Error 2
```

I tried installing firefox-pkcs11-loader from the kentaur repo, but it has zero effect. I do have the opensc package installed.

Anything I can do to debug this?

**Comment by metsma** [comment]
`make installer` knows only how to make Window/macOS/ubuntu package.
Use `make install` for other cases.
Here is wiki how to configure firefox manualy
https://github.com/OpenSC/OpenSC/wiki/Installing-OpenSC-PKCS%2311-Module-in-Firefox,-Step-by-Step

**Comment by tari3x** [comment]
Turned out I had to install the appropriate pcsc driver for my system. This was a random guess. Would it be possible to document it somewhere discoverable, and document an easy test that users can use to check if they need drivers? In my case, running pcsc_scan would hang before installing the driver, and would print a bunch of info afterwards.

**Comment by metsma** [comment]
opensc-pkcs11 should install needed requirements.
Feel free open bugreports to SuSe OpenSC maintainer

**Comment by tari3x** [comment]
Sorry, I am not sufficiently informed or motivated to open such a bug report. I have solved this particular problem for myself already, and I wouldn't know what to say to the upstream maintainers exactly.

I was hoping you'd be motivated to make sure that your package works well on all major platforms. Besides, I expect you to have a lot more expertise than me, and be able to explain much better to the OpenSC maintainer what the problem is.
