### ISSUE TITLE
not compatible with Firefox 58 Quantum

### ISSUE THREAD

**Issue by nekromoff** [open-eid/firefox-pkcs11-loader#9]
![obrazok](https://user-images.githubusercontent.com/8550349/36448485-13ad27c6-1688-11e8-88e9-2d358ff3fbf4.png)

**Comment by markus-kullerkup** [comment]
"Estonian ID Card PKSCS11 module" add-on was removed due availabilty of the add-on "Estonian ID Card authentication module" which serves the same function.
